refactor(dicom.pixels.clean): remove image_type
This could be a breaking change if it `image_type='original'` was ever
valid. I don't think it is (more below).
`image_type` can/should likely be removed from all other save_*
functions too.

Ostensibly, the option existed to look into the original pixel_array.
But `clean_pixel_data` is the only place I see with that variable and
it is run as an isolated function w/ no access to the DicomCleaner object.

DicomCleaner has no `original` attribute.
```
(Pdb) self.__dir__()
['font', 'cmap', 'output_folder', 'recipe', 'results', 'force', 'dicom_file', 'cleaned', '__module__', '__doc__', '__init__', 'default_font', 'detect', 'clean', 'get_figure', '_get_clean_name', 'save_png', 'save_animation', 'save_dicom', '__dict__', '__weakref__', '__new__', '__repr__', '__hash__', '__str__', '__getattribute__', '__setattr__', '__delattr__', '__lt__', '__le__', '__eq__', '__ne__', '__gt__', '__ge__', '__reduce_ex__', '__reduce__', '__getstate__', '__subclasshook__', '__init_subclass__', '__format__', '__sizeof__', '__dir__', '__class__']
(Pdb) self.original
*** AttributeError: 'DicomCleaner' object has no attribute 'original'
````